---
active_modules: [tags, pygments, blog, disqus, analytics]
author: Marcin Wielgoszewski
canonical_url: 'http://www.tssci-security.com/'
modules:
  pygments:
      style: trac
template: base.html
modules.blog.per_page: 5
modules.blog.archive_url: '/archives/'
modules.blog.year_archive_url: '/archives/<year>/'
modules.blog.month_archive_url: '/archives/<year>/<month>/'
modules.blog.feed_url: '/feed.atom'
modules.blog.sitemap_url: '/861357e24d84cfa8997124173926437a0eac8fbc.html'
feed.name: tssci-security
feed.subtitle: top secret/secure computing information
modules.disqus.shortname: tssci-security-s0
#modules.disqus.developer: true
modules.analytics.id: UA-128103-7
modules.analytics.url: tssci-security.com
modules.blog.mainmenu:
    - ['/', 'Home']
    - ['/about/', 'About']
    - ['/projects/', 'Projects']
    - ['/research/', 'Research']
modules.tags.tag_url: '/archives/category/<tag>/'
modules.tags.tag_feed_url: '/archives/category/<tag>/feed.atom'
modules.tags.cloud_url: '/archives/category/'
